### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by thoni56** [cividesk/com.cividesk.l10n.update#13]
There is no information about how this should be installed. It seems not to be packaged, which means a user must have more than casual knowledge on how CiviCRM internals work.

Could we at least have a section in the README about this?

**Comment by eptbertram** [comment]
Dear @thoni56, the system admin guide, section Extensions, applies here: https://docs.civicrm.org/sysadmin/en/latest/customize/extensions/#installing-a-new-extension 

Important to know: you need a directory named l10n with sufficent rights in order to get the extension working. 

Maybe you like to close this issue with these information given? Or you may add these information to the readme-file on Github yourself.

**Comment by thoni56** [comment]
Well, since there is no package (zip, tar) I'm assuming you just copy all the files into the extension directory. Or even clone the repo there?

**Comment by eptbertram** [comment]
Yes, there are no releases published. Just download the ZIP (green button "Code" on the right top) and transfer it to your server.

**Comment by thoni56** [comment]
Updated the PR.
